spring.application.name=apiusuarios

# Endereco do banco H2 em memoria.
# "mem" significa: fica na memoria e some quando a aplicacao para.
spring.datasource.url=jdbc:h2:mem:apiusuarios

# Driver usado pelo Java para conversar com o H2.
spring.datasource.driverClassName=org.h2.Driver

# Usuario padrao do H2.
spring.datasource.username=sa

# Senha do H2.
# Neste estudo, vamos deixar vazia.
spring.datasource.password=

# Pede para o Hibernate atualizar/criar as tabelas automaticamente no estudo.
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal os SQLs executados.
spring.jpa.show-sql=true

# Liga a tela web do H2.
spring.h2.console.enabled=true

# Caminho para acessar no navegador: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console
